name: Python runner
on: push
jobs:
  test_ui:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          Python_Playwright_ReportalPortal
    - name: Installing Playwright
      run: pip install pytest-playwright
    - name: Installing Playwright browser Chrome
      run: playwright install --with-deps chromium
    - name: Installing Python library's from requirements.txt
      run: |
        cd Python_Playwright_ReportalPortal
        pip3 install -r requirements.txt
    - name: Running UI Tests by PyTest
      run: |
        cd Python_Playwright_ReportalPortal
        xvfb-run pytest tests/tests_ui/tests_ui.py::TestsSignInPage
    - name: HTML Report
      run: ls
      uses: actions/upload-artifact@v3
      with:
        name: Report
        path: /Python_Playwright_ReportalPortal/report.html