name: Python runner
on: push
jobs:
  test_ui:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          Python_Playwright_ReportalPortal
    - name: Installing Python library's from requirements.txt
      run: |
        cd Python_Playwright_ReportalPortal
        pip3 install -r requirements.txt
    - name: Running UI Tests
      run: pwd
