name: Python runner
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Python3 version
      run: python3 --version
    - name: Python packages
      run: pip3 freeze
